### ISSUE TITLE
Ban by IP instead of GUID?

### ISSUE THREAD

**Issue by eemmbb** [ozguruysal/b3-plugin-aimbotdetector#2]
Probably a longshot since this is an old plugin, but do you think if it would be possible to have an additional option which would only ban the players IP address instead of GUID. This would be helpful for cracked servers,  since multiple players are often using the same guid and innocent players will be banned on top of the actual cheater.

Thanks!

**Comment by ozguruysal** [comment]
IP addresses are generally dynamic and you'd be banning more innocent players or the ban wouldn't work when the player resets the router. As far as I remember B3 core wouldn't support that. I guess those "innocent" players should get legitimate copies of games to avoid such problems 😉
